/** A record of the local catalog, as generated by tools/catalog. */
export interface CatalogFilm {
  title: string;
  originalTitle: string;
  year: number;
  director: string;
  /** Letterboxd-style slug; the catalog identity. */
  slug: string;
  runtime: number;
  /** Empty when the source only knew a placeholder such as "Internacional". */
  country: string;
  /** ISO 639-1 code when known (for example "pt" or "en"). */
  originalLanguage?: string;
  /** Provenance of descriptive terms; genre synonyms are not facts about a film. */
  keywordEvidence?: KeywordEvidence[];
  runtimeKnown?: boolean;
  imdbRating: number;
  imdbVotes: number;
  imdbId: string;
  themes: string[];
  genres: string[];
  keywords: string[];
  pitch: string;
}

export interface KeywordEvidence {
  term: string;
  source: 'film' | 'genre' | 'director' | 'derived' | 'legacy';
}

export type DiscoveryMode = 'familiar' | 'explore' | 'surprise';
export type FeedbackKind = 'later' | 'not-for-me' | 'watched';
export interface FilmFeedback {
  username: string;
  film: FilmIdentity;
  kind: FeedbackKind;
  createdAt: string;
}

/** A film as it appears in a user's history (web sync, RSS or CSV import). */
export interface ProfileFilm {
  title: string;
  slug?: string;
  year?: number | null;
  rating?: number | null;
  isFavorite?: boolean;
  source?: string;
  originalTitle?: string;
  catalogSlug?: string;
  letterboxdSlug?: string;
  letterboxdUri?: string;
  link?: string;
  watchedDate?: string | null;
  watchedThisYear?: boolean;
  director?: string;
  genres?: string[];
  keywords?: string[];
  keywordEvidence?: KeywordEvidence[];
  pitch?: string;
  runtime?: number | null;
  country?: string;
}

/** A profile film completed with catalog metadata when its identity is safe. */
export interface EnrichedFilm extends ProfileFilm {
  catalogSlug: string;
  catalogTitleAmbiguous: boolean;
  director: string;
  genres: string[];
  keywords: string[];
  runtime: number | null;
  country: string;
}

export interface UserProfile {
  username: string;
  displayName?: string;
  bio?: string;
  avatarUrl?: string;
  totalFilms?: number;
  filmCountKnown?: boolean;
  thisYearCount?: number;
  thisYearFilms?: ProfileFilm[];
  favorites?: ProfileFilm[];
  films: ProfileFilm[];
  lastSync?: string;
  lastFullSync?: string | null;
  syncMode?: 'full' | 'recent';
  csvIdentityVersion?: number;
  csvDuplicatesRemoved?: number;
}

/** What is needed to decide whether two records are the same film. */
export interface FilmIdentity {
  title?: string;
  originalTitle?: string;
  year?: number | string | null;
  slug?: string;
  letterboxdSlug?: string;
  catalogSlug?: string;
}

export type RuntimeFilter =
  | 'under-60'
  | 'under-90'
  | 'under-105'
  | 'under-120'
  | '90-120'
  | 'over-120'
  | 'over-150';

export interface Filters {
  avoidWatched?: boolean;
  includeUnderrated?: boolean;
  minVotes?: number;
  minYear?: number | null;
  maxYear?: number | null;
  runtimeFilter?: RuntimeFilter | '';
  maxRuntime?: number;
  minRuntime?: number;
  nicheOnly?: boolean;
  /** Earlier recommendations, kept out of thematic browsing for variety. */
  excludeRecent?: FilmIdentity[];
}

export interface Settings {
  avoidWatched: boolean;
  includeUnderrated: boolean;
  minVotes: number;
}

export interface Recommendation {
  title: string;
  originalTitle: string;
  year: number;
  director: string;
  letterboxdSlug: string;
  catalogSlug: string;
  /** A film URL when the Letterboxd identity is known; otherwise a search URL. */
  letterboxdUrl: string;
  posterPath: string;
  pitch: string;
  runtimeMinutes: number;
  country: string;
  genres: string[];
  imdbRating: number;
  /** Why the film fits the user's taste, when it does. */
  affinityReason: string | null;
}

export interface RecommendationResult {
  themeName: string;
  curatorComment: string;
  /** Only what the viewer should know about this result (a widened search, no match); else ''. */
  notice: string;
  recommendations: Recommendation[];
  /** True when earlier recommendations had to be reused to fill the list. */
  allowRecentFallback: boolean;
  /** Conditions actually applied to the request, in pt-BR. */
  interpretation?: string[];
}

export interface YearPhaseSummary {
  currentYear: number;
  thisYearCount: number;
  topGenres: { genre: string; count: number }[];
  phaseDescription: string;
}

export interface DailyPick {
  /** YYYY-MM-DD in the pick's time zone. */
  date: string;
  matchingVersion: number;
  film: Recommendation & { imdbRating: number; imdbVotes: number; vibeKeywords: string[] };
  curatorReason: string;
  phaseInfo: YearPhaseSummary;
}
