/**
 * Completes posters, real synopses, countries and original languages through
 * TMDB. Progress is checkpointed and can safely be resumed.
 *
 * PowerShell:
 *   $env:TMDB_READ_ACCESS_TOKEN="..."; npm run catalog:tmdb
 * Optional:
 *   $env:TMDB_BATCH_LIMIT="100"; npm run catalog:tmdb
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { EXPANDED_FILM_DATABASE } from '../../src/data/films-dataset.js';
import { isGenericPitch, mergeTmdbMetadata, metadataFromTmdb, selectMovieResult } from './tmdb-enrichment.js';

const dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(dirname, '..', '..');
const datasetPath = path.join(root, 'src', 'data', 'films-dataset.js');
const posterPath = path.join(root, 'src', 'data', 'poster-catalog.js');
const checkpointPath = path.join(dirname, 'tmdb-checkpoint.json');
const token = process.env.TMDB_READ_ACCESS_TOKEN || '';
const limit = Number.parseInt(process.env.TMDB_BATCH_LIMIT || '', 10) || Infinity;
const delayMs = Number.parseInt(process.env.TMDB_DELAY_MS || '', 10) || 110;
const concurrency = Number.parseInt(process.env.TMDB_CONCURRENCY || '', 10) || 64;
const checkpointEvery = Number.parseInt(process.env.TMDB_CHECKPOINT_EVERY || '', 10) || 256;

const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

function readJson(file, fallback = {}) {
  return fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : fallback;
}

function readPosterMap() {
  if (!fs.existsSync(posterPath)) return {};
  const source = fs.readFileSync(posterPath, 'utf8');
  const start = source.indexOf('{');
  const end = source.lastIndexOf('}');
  if (start < 0 || end < start) throw new Error('poster-catalog.js inválido.');
  return JSON.parse(source.slice(start, end + 1));
}

function saveDataset(films) {
  const rows = films.map(film => `  ${JSON.stringify(film)}`).join(',\n');
  fs.writeFileSync(datasetPath, `export const EXPANDED_FILM_DATABASE = [\n${rows}\n];\n`, 'utf8');
}

function savePosters(posters) {
  const ordered = Object.fromEntries(Object.entries(posters).sort(([a], [b]) => a.localeCompare(b)));
  const source = [
    '// Generated by tools/catalog/enrich-tmdb.js. Do not add credentials here.',
    'export const POSTER_PATHS_BY_IMDB_ID = Object.freeze(',
    JSON.stringify(ordered, null, 2),
    ');',
    ''
  ].join('\n');
  fs.writeFileSync(posterPath, source, 'utf8');
}

function saveProgress(films, posters, checkpoint) {
  saveDataset(films);
  savePosters(posters);
  fs.writeFileSync(checkpointPath, JSON.stringify(checkpoint, null, 2), 'utf8');
}

async function tmdb(endpoint, params = {}, { allowNotFound = false } = {}) {
  const url = new URL(`https://api.themoviedb.org/3${endpoint}`);
  for (const [key, value] of Object.entries(params)) url.searchParams.set(key, String(value));
  for (let attempt = 0; attempt < 4; attempt++) {
    const response = await fetch(url, {
      headers: { Authorization: `Bearer ${token}`, Accept: 'application/json' },
      signal: AbortSignal.timeout(15000)
    });
    if (response.ok) return response.json();
    if (allowNotFound && response.status === 404) return null;
    if (response.status !== 429 && response.status < 500) throw new Error(`TMDB respondeu HTTP ${response.status}`);
    await sleep(500 * (attempt + 1));
  }
  throw new Error('TMDB indisponível após quatro tentativas.');
}

async function fetchMetadata(imdbId) {
  const found = await tmdb(`/find/${encodeURIComponent(imdbId)}`, { external_source: 'imdb_id', language: 'pt-BR' });
  const result = selectMovieResult(found);
  if (!result) return { tmdbId: null, posterPath: null, pitch: '', country: '', originalLanguage: '' };
  await sleep(delayMs);
  const detailsPt = await tmdb(`/movie/${result.id}`, { language: 'pt-BR' }, { allowNotFound: true });
  let detailsEn = null;
  if (detailsPt && !String(detailsPt.overview || '').trim()) {
    await sleep(delayMs);
    detailsEn = await tmdb(`/movie/${result.id}`, { language: 'en-US' }, { allowNotFound: true });
  }
  return metadataFromTmdb(result, detailsPt, detailsEn);
}

async function main() {
  if (!token) throw new Error('TMDB_READ_ACCESS_TOKEN não configurado.');

  const films = EXPANDED_FILM_DATABASE.map(film => ({ ...film }));
  const posters = readPosterMap();
  const checkpoint = readJson(checkpointPath);
  const byImdbId = new Map(films.map((film, index) => [film.imdbId, index]));

  for (const [imdbId, metadata] of Object.entries(checkpoint)) {
    const index = byImdbId.get(imdbId);
    if (index !== undefined) films[index] = mergeTmdbMetadata(films[index], metadata);
    if (!Object.hasOwn(posters, imdbId)) posters[imdbId] = metadata.posterPath ?? null;
  }

  const pending = films.filter(film => {
    const needsMetadata = isGenericPitch(film.pitch) || !film.country || film.country === 'Internacional' || !film.originalLanguage;
    return !Object.hasOwn(checkpoint, film.imdbId) && (needsMetadata || !Object.hasOwn(posters, film.imdbId));
  }).slice(0, limit);

  console.log(`Catálogo: ${films.length} filmes · checkpoint: ${Object.keys(checkpoint).length} · processando: ${pending.length}`);
  let matched = 0;
  let unmatched = 0;

  for (let offset = 0; offset < pending.length; offset += concurrency) {
    const batch = pending.slice(offset, offset + concurrency);
    const results = await Promise.all(batch.map(async film => ({ film, metadata: await fetchMetadata(film.imdbId) })));
    for (const { film, metadata } of results) {
      checkpoint[film.imdbId] = metadata;
      posters[film.imdbId] = metadata.posterPath;
      const filmIndex = byImdbId.get(film.imdbId);
      films[filmIndex] = mergeTmdbMetadata(films[filmIndex], metadata);
      metadata.tmdbId ? matched++ : unmatched++;
    }
    const processed = Math.min(offset + batch.length, pending.length);
    if (processed % checkpointEvery === 0 || processed === pending.length) saveProgress(films, posters, checkpoint);
    if (processed % 128 === 0 || processed === pending.length) {
      process.stdout.write(`\r${processed}/${pending.length} · ${matched} encontrados · ${unmatched} sem resultado`);
    }
    await sleep(delayMs);
  }

  saveProgress(films, posters, checkpoint);
  console.log('\nConcluído. O comando pode ser executado novamente para retomar.');
}

main().catch(error => {
  console.error(`\nErro: ${error.message}`);
  process.exitCode = 1;
});
