import type { PosterPaths } from '../domain/catalog/catalog.ts';

/** TMDB poster paths by IMDb id (null when TMDB had none). Generated by tools/catalog. */
export declare const POSTER_PATHS_BY_IMDB_ID: PosterPaths;
